name: Build and Deploy service

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build service
    steps:
      - name: Build service
        run: |
          echo "Building service ${{inputs.service}}"

  deploy:
    name: Deploy service
    needs: build
    strategy:
      fail-fast: false
      matrix:
        region: ["eu", "india"]
        environment: ["dev", "prod"]
    uses: ./.github/workflows/deploy.yaml
    with:
      region: ${{ matrix.region }}
      environment: ${{ matrix.environment }}
      service: ${{ inputs.service }}
    secrets: inherit
