name: Telemetry Data Pipeline Release

on:
  push: ~

jobs:
  detect-changed-services:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          dir_names_exclude_root: true
          dir_names_max_depth: 1
          files_ignore: |
            .github/*
          json: true

      - name: List all changed files
        id: list-all
        run: |
            echo "changed=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT

    outputs:
      changed_services: ${{ steps.list-all.outputs.changed }}


  build-services:
    name: Build and deploy changed services
    needs: detect-changed-services
    strategy:
      fail-fast: false
      matrix:
        changed_services: ${{ fromJSON(needs.detect-changed-services.outputs.changed_services) }}
    uses: ./.github/workflows/build_and_deploy.yaml
    with:
      service: ${{ matrix.changed_services }}

  deploy-services-dev:
    name: Deploy services to dev
    needs: 
      - detect-changed-services
      - build-services
    strategy:
      fail-fast: false
      matrix:
        changed_services: ${{ fromJSON(needs.detect-changed-services.outputs.changed_services) }}
        region: ["eu", "india"]
    uses: ./.github/workflows/deploy.yaml
    with:
      region: ${{ matrix.region }}
      environment: "dev"
      service: ${{ inputs.service }}
    secrets: inherit

  deploy-services-prod:
    name: Deploy services to prod
    needs: 
      - detect-changed-services
      - build-services
      - deploy-services-dev
    strategy:
      fail-fast: false
      matrix:
        changed_services: ${{ fromJSON(needs.detect-changed-services.outputs.changed_services) }}
        region: ["eu", "india"]
    uses: ./.github/workflows/deploy.yaml
    with:
      region: ${{ matrix.region }}
      environment: "prod"
      service: ${{ inputs.service }}
    secrets: inherit

