name: Telemetry Data Pipeline Release

on:
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          dir_names_max_depth: 1

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: trigger svc-a publish
        if: contains(steps.changed-files.outputs.all_changed_files, 'svc-a')
        run: |
          echo "Svc-a was changed"

      - name: trigger svc-b publish
        if: contains(steps.changed-files.outputs.all_changed_files, 'svc-b')
        run: |
          echo "Svc-b was changed"

      - name: trigger svc-c publish
        if: contains(steps.changed-files.outputs.all_changed_files, 'svc-c')
        run: |
          echo "Svc-c was changed"
